### ISSUE TITLE
broken images 

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/2021-11-04-ucsb-sql-online#3]
I think we are missing some of the figures

example page: https://ucsbcarpentry.github.io/2021-11-04-ucsb-sql-online/02-common-mistakes/index.html

**Comment by kristi-sara** [comment]
I saw those earlier thanks for putting in an issue

**Comment by kristi-sara** [comment]
I'm having a hard time tracking down the original lessons where we pulled the episodes (esp since we renumbered). Which ones did we pull from dc-socsci vs swc-novice-survey (or anything else?).

**Comment by kristi-sara** [comment]
I went through all the lessons and fixed the image links. closing issue now.
